### ISSUE TITLE
UndefinedError: 'monthNameShort' is undefined

### ISSUE THREAD

**Issue by fi-sch** [maykar/custom-header#212]
Hey!

I have those annoying errors in Logs for a quite long time now and see that it still persist after several HA and Custom Header updates so I'm reporting that.
It's not a functional issue, I did not notice any unexpected behaviour apart from those log entries that seem to reappear a few times a day.

Here's the whole entry:
```
Logger: homeassistant.components.websocket_api.http.connection.140067111809168
Source: helpers/template.py:230 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 9:12:18 (1 occurrences) 
Last logged: 9:12:18

Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 228, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/site-packages/jinja2/sandbox.py", line 384, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'monthNameShort' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 265, in handle_render_template
    state_listener()
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 253, in state_listener
    msg["id"], {"result": template.async_render(variables)}
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 230, in async_render
    raise TemplateError(err)
homeassistant.exceptions.TemplateError: UndefinedError: 'monthNameShort' is undefined
```

And here's my CH config:
```
custom_header:
  button_text:
    options: >-
      {{ time }}<br>{{ dayNum }}  {{ monthNameShort[0]|upper }}{{
      monthNameShort[1:] }}
  chevrons: false
  compact_mode: true
  editor_warnings: false
  hide_help: false
  menu_hide: true
swipe_nav:
  prevent_default: true
  swipe_amount: 30
  wrap: true
```

No relevant errors in browser. Latest HA and CH version. Installation via HACS.

**Comment by maykar** [comment]
Looking into it, but is there any reason that you're manually capitalizing monthNameShort?

It should already be capitalized, so this should result in the same:

```
  button_text:
    options: >-
      {{ time }}<br>{{ dayNum }}  {{ monthNameShort }}
```

**Comment by fi-sch** [comment]
Thanks for quick reaction!

Unfortunately I'm using polish language and it's not capitalized when I use {{ monthNameShort }} :(  That's why I capitalized it manually.

**Comment by maykar** [comment]
Please, try the latest pre-release ( 1.5.2 ) and let me know if it helps. To install pre-releases with HACS use the menu on the bottom right of Custom Headers listing to reinstall and turn on "Show beta versions".

**Comment by fi-sch** [comment]
Ok. I've just reinstalled the pre-release 1.5.2 and it seems that the issue did not re-appear. I will check on that also later today and let you know about the outcome. Thanks! :)

**Comment by fi-sch** [comment]
Unfortunately it just re-appeared, twice:

```
Logger: homeassistant.components.websocket_api.http.connection.140149204098256
Source: helpers/template.py:230 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 15:29:25 (2 occurrences) 
Last logged: 15:29:25

Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 228, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/site-packages/jinja2/sandbox.py", line 384, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'monthNameShort' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 265, in handle_render_template
    state_listener()
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 253, in state_listener
    msg["id"], {"result": template.async_render(variables)}
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 230, in async_render
    raise TemplateError(err)
homeassistant.exceptions.TemplateError: UndefinedError: 'monthNameShort' is undefined
```

**Comment by maykar** [comment]
Can't seem to recreate this one. Have added your config to my setup since you first reported this issue and have yet to see this error. I changed up how templates are returned to make sure that they are always defined as I thought that might be an issue, but it seems that didn't do it for you.

Some suggestions that may sound silly, but:
* Make sure you're not using this template outside of CH
* Double check that all devices with HA open have been refreshed
* Ensure that when looking in your browsers dev tools console (F12) that version 1.5.2 is being reported.

Beyond that, is there any pattern to when this error pops up? Like only when entering edit mode or when switching to a new tab, etc.

**Comment by maykar** [comment]
I've even added a fake template variable that definitely doesn't exist in the template called {{ doesntExist }} to try and force the error, but I still get none.

**Comment by maykar** [comment]
Okay so if I use the fake variable with modifications like: {{ doesntExist[1:] }} I can force the issue, and if I downgrade to 1.5.1 I can get this error with just {{ monthNameShort[0]|upper }}.

So definitely check that you have closed/refreshed tabs/devices that have been open before the update and ensure that your console dev tools report version 1.5.2

**Comment by fi-sch** [comment]
Ok, that was my bad. So I did close all the HA tabs running in background in my browser, cleared the cache. I also checked if I'm running 1.5.2.
It seems that this issue does not pop-up any more. I will let you know if it will show up again – hopefully it will not :) Thanks!

**Comment by maykar** [comment]
Going to close this for now as I was able to recreate the issue and it seems resolved in the latest, but feel free to continue to post here if this continues to be an issue. Thanks!
